import type { SeedTicket } from "./seed-ticket.ts";

export const checkoutTickets: SeedTicket[] = [
  {
    id: "CHK-101",
    title: "Apple Pay sheet closes without charging on Safari 18",
    description:
      "Customers on Safari 18.1 see the Apple Pay sheet open and immediately dismiss. No charge is created and nothing reaches Sentry. Reproducible on an iPhone 15 with a Visa card; Mastercard works.",
    status: "in_progress",
    priority: "urgent",
    assigneeId: "diego-alvarez",
    createdDaysAgo: 4,
    updatedHoursAgo: 2,
  },
  {
    id: "CHK-102",
    title: "Show the delivery estimate before the payment step",
    description:
      "Support gets a steady stream of 'when will it arrive?' questions after purchase. Move the delivery window from the confirmation page to the shipping step so customers see it before they pay.",
    status: "open",
    priority: "medium",
    assigneeId: null,
    createdDaysAgo: 21,
    updatedHoursAgo: 72,
  },
  {
    id: "CHK-103",
    title: "Promo codes are case-sensitive",
    description:
      "SPRING25 works but spring25 returns 'code not found'. Codes should match regardless of case; marketing prints them in lowercase on the flyers.",
    status: "closed",
    priority: "medium",
    assigneeId: "priya-nair",
    createdDaysAgo: 30,
    updatedHoursAgo: 480,
  },
  {
    id: "CHK-104",
    title: "Cart total flickers to $0.00 while shipping is recalculated",
    description:
      "When the customer changes the shipping country, the total briefly renders as $0.00 before the new rates arrive. Keep showing the previous total with a loading indicator instead.",
    status: "in_progress",
    priority: "low",
    assigneeId: "lena-fischer",
    createdDaysAgo: 9,
    updatedHoursAgo: 5,
  },
  {
    id: "CHK-105",
    title: "Stripe webhook retries send duplicate confirmation emails",
    description:
      "If our webhook handler times out, Stripe retries and we send a second order confirmation. The handler needs to be idempotent on the event id. Blocked until the platform team ships the shared idempotency table.",
    status: "blocked",
    priority: "high",
    assigneeId: "diego-alvarez",
    createdDaysAgo: 12,
    updatedHoursAgo: 26,
  },
  {
    id: "CHK-106",
    title: "Add PayPal Pay Later messaging to the cart page",
    description:
      "Finance approved Pay Later for orders over $50. Add the PayPal messaging component under the cart total, behind the paylater_messaging flag.",
    status: "open",
    priority: "medium",
    assigneeId: null,
    createdDaysAgo: 15,
    updatedHoursAgo: 96,
  },
  {
    id: "CHK-107",
    title: "Address autocomplete drops apartment numbers",
    description:
      "Picking a suggestion from the address autocomplete throws away the unit number the customer already typed. About 3% of failed deliveries last month trace back to this.",
    status: "in_progress",
    priority: "high",
    assigneeId: "priya-nair",
    createdDaysAgo: 7,
    updatedHoursAgo: 20,
  },
  {
    id: "CHK-108",
    title: "Guest checkout asks for a password twice",
    description:
      "The 'create an account' option on the confirmation step still shows two password fields, even though we dropped the confirm-password requirement in March.",
    status: "closed",
    priority: "low",
    assigneeId: "lena-fischer",
    createdDaysAgo: 40,
    updatedHoursAgo: 792,
  },
  {
    id: "CHK-109",
    title: "Tax summary is missing QST for Quebec orders",
    description:
      "Orders shipping to Quebec show 5% GST only; the 9.975% QST line is missing from the summary even though the charge itself is correct. Customers are emailing support about the mismatch.",
    status: "open",
    priority: "high",
    assigneeId: "diego-alvarez",
    createdDaysAgo: 3,
    updatedHoursAgo: 9,
  },
  {
    id: "CHK-110",
    title: "Payment step is hard to use with VoiceOver",
    description:
      "The card number iframe has no accessible label, and focus jumps back to the top of the page after each field. Found during the quarterly accessibility audit.",
    status: "open",
    priority: "high",
    assigneeId: "maya-chen",
    createdDaysAgo: 10,
    updatedHoursAgo: 30,
  },
  {
    id: "CHK-111",
    title: "Remember the last used shipping method",
    description:
      "Returning customers always land on Standard shipping, even if they chose Express last time. Preselect the method from their previous order when it is still available.",
    status: "open",
    priority: "low",
    assigneeId: null,
    createdDaysAgo: 45,
    updatedHoursAgo: 288,
  },
  {
    id: "CHK-112",
    title: "3-D Secure challenge times out on slow connections",
    description:
      "The 3DS challenge gives up after 15 seconds. On mobile networks banks regularly take longer, and the order fails with a generic error. Waiting on Adyen to confirm the maximum timeout we can set.",
    status: "blocked",
    priority: "urgent",
    assigneeId: "maya-chen",
    createdDaysAgo: 6,
    updatedHoursAgo: 8,
  },
  {
    id: "CHK-113",
    title: "Gift cards cannot be combined with promo codes",
    description:
      "Applying a promo code removes a gift card that was already applied. The business rule is that both can be used together, with the promo applied first.",
    status: "in_progress",
    priority: "medium",
    assigneeId: "lena-fischer",
    createdDaysAgo: 11,
    updatedHoursAgo: 24,
  },
  {
    id: "CHK-114",
    title: "Order confirmation shows raw currency codes",
    description:
      "Totals render as 'USD 42.00' instead of '$42.00' for customers with a non-US browser locale. Format amounts with the store currency, not the browser locale.",
    status: "closed",
    priority: "low",
    assigneeId: "priya-nair",
    createdDaysAgo: 25,
    updatedHoursAgo: 100,
  },
  {
    id: "CHK-115",
    title: "Send declined payment reasons to the risk team",
    description:
      "Risk wants decline codes (insufficient funds, suspected fraud, and so on) in the analytics pipeline so they can tune their rules. Card details must stay out of the event.",
    status: "open",
    priority: "medium",
    assigneeId: "diego-alvarez",
    createdDaysAgo: 18,
    updatedHoursAgo: 144,
  },
  {
    id: "CHK-116",
    title: "Saved cards list shows expired cards first",
    description:
      "Show the default card first, then the rest by most recently used. Hide cards that expired more than a year ago.",
    status: "open",
    priority: "low",
    assigneeId: null,
    createdDaysAgo: 33,
    updatedHoursAgo: 216,
  },
  {
    id: "CHK-117",
    title: "Checkout crashes when the cart has a discontinued item",
    description:
      "If an item is discontinued between add-to-cart and checkout, the order summary throws and the page goes blank. Remove the item and tell the customer why instead.",
    status: "closed",
    priority: "urgent",
    assigneeId: "diego-alvarez",
    createdDaysAgo: 14,
    updatedHoursAgo: 312,
  },
  {
    id: "CHK-118",
    title: "Free shipping banner uses the pre-discount subtotal",
    description:
      "The 'You're $8 away from free shipping' banner counts the subtotal before discounts, but the threshold is applied after them. Customers think they qualify and then get charged for shipping.",
    status: "in_progress",
    priority: "medium",
    assigneeId: "maya-chen",
    createdDaysAgo: 5,
    updatedHoursAgo: 3,
  },
  {
    id: "CHK-119",
    title: "Offer Klarna to customers in Germany",
    description:
      "Klarna is the most requested payment method in German support tickets. Scope: Pay in 30 days only, orders up to €1,000, behind a country flag. Blocked on legal review of the updated terms.",
    status: "blocked",
    priority: "medium",
    assigneeId: "priya-nair",
    createdDaysAgo: 28,
    updatedHoursAgo: 168,
  },
  {
    id: "CHK-120",
    title: "Checkout loads 1.2 MB of JavaScript it does not need yet",
    description:
      "Lighthouse flags the address validation and PayPal SDKs loading upfront. Load each one when the customer reaches the step that uses it.",
    status: "open",
    priority: "medium",
    assigneeId: "lena-fischer",
    createdDaysAgo: 20,
    updatedHoursAgo: 50,
  },
  {
    id: "CHK-121",
    title: "Order summary keeps the old total after removing an item",
    description:
      "Removing an item from the mini cart on the payment step leaves the previous total in the order summary until the page is refreshed.",
    status: "closed",
    priority: "high",
    assigneeId: "lena-fischer",
    createdDaysAgo: 16,
    updatedHoursAgo: 360,
  },
  {
    id: "CHK-122",
    title: "Explain declined cards in plain language",
    description:
      "Declines currently show 'Something went wrong'. Map the common decline codes to clear messages and suggest trying another card or payment method.",
    status: "in_progress",
    priority: "high",
    assigneeId: "diego-alvarez",
    createdDaysAgo: 8,
    updatedHoursAgo: 6,
  },
  {
    id: "CHK-123",
    title: "Postcode validation rejects valid UK postcodes",
    description:
      "Postcodes typed without a space, like SW1A1AA, fail validation. Normalise the input before validating instead of asking customers to reformat it.",
    status: "open",
    priority: "medium",
    assigneeId: null,
    createdDaysAgo: 2,
    updatedHoursAgo: 40,
  },
  {
    id: "CHK-124",
    title: "Add an order notes field for business customers",
    description:
      "B2B customers want to add a PO number or delivery instructions. Add an optional 500-character notes field to the shipping step and include it in the order export.",
    status: "open",
    priority: "low",
    assigneeId: "priya-nair",
    createdDaysAgo: 50,
    updatedHoursAgo: 528,
  },
  {
    id: "CHK-125",
    title: "Double-clicking 'Place order' creates two orders",
    description:
      "Two customers were charged twice this week. Disable the button while the order is submitting and make the endpoint reject duplicate submissions.",
    status: "closed",
    priority: "urgent",
    assigneeId: "maya-chen",
    createdDaysAgo: 9,
    updatedHoursAgo: 46,
  },
  {
    id: "CHK-126",
    title: "Switching currency empties the cart",
    description:
      "Changing from EUR to GBP in the footer clears every item from the cart. Prices should be converted and the items kept.",
    status: "open",
    priority: "high",
    assigneeId: "lena-fischer",
    createdDaysAgo: 4,
    updatedHoursAgo: 11,
  },
  {
    id: "CHK-127",
    title: "Track checkout drop-off per step",
    description:
      "Product wants to see where customers abandon checkout. Emit a step_viewed event with the step name and cart value, and no personal data.",
    status: "in_progress",
    priority: "medium",
    assigneeId: "priya-nair",
    createdDaysAgo: 13,
    updatedHoursAgo: 28,
  },
  {
    id: "CHK-128",
    title: "'Billing same as shipping' unchecks itself after going back",
    description:
      "The option is checked by default, but navigating back from the payment step unchecks it and shows an empty billing address form.",
    status: "open",
    priority: "low",
    assigneeId: null,
    createdDaysAgo: 6,
    updatedHoursAgo: 60,
  },
  {
    id: "CHK-129",
    title: "Retire the legacy /checkout/v1 endpoints",
    description:
      "Less than 0.5% of traffic still hits v1, all of it from mobile app versions below 5.2. Remove the routes, the feature flag and the v1 tests once the app forces the upgrade.",
    status: "blocked",
    priority: "low",
    assigneeId: "diego-alvarez",
    createdDaysAgo: 35,
    updatedHoursAgo: 240,
  },
  {
    id: "CHK-130",
    title: "Failed payment page has no way back to the cart",
    description:
      "When an order fails after the payment is authorised, the error page has no link back to the cart or to support. Add both, and show the order reference.",
    status: "open",
    priority: "medium",
    assigneeId: "maya-chen",
    createdDaysAgo: 1,
    updatedHoursAgo: 1,
  },
];
