import type { SeedTicket } from "./seed-ticket.ts";

export const mobileAppTickets: SeedTicket[] = [
  {
    id: "MOB-201",
    title: "App crashes on launch on Android 15 Pixel devices",
    description:
      "The crash rate on Pixel 8 and 9 devices running Android 15 jumped to 4% after 5.3.0. The stack trace points at the splash screen migration.",
    status: "in_progress",
    priority: "urgent",
    assigneeId: "sam-okafor",
    createdDaysAgo: 2,
    updatedHoursAgo: 1,
  },
  {
    id: "MOB-202",
    title: "Push notifications arrive twice on iOS",
    description:
      "Users who have both the old and the new notification token registered get every order update twice. Remove the legacy token once the new one is confirmed.",
    status: "open",
    priority: "high",
    assigneeId: "hana-kim",
    createdDaysAgo: 8,
    updatedHoursAgo: 18,
  },
  {
    id: "MOB-203",
    title: "Unlock the app with Face ID or fingerprint",
    description:
      "Let returning users sign in with biometrics instead of typing their password. Fall back to the password after three failed attempts.",
    status: "in_progress",
    priority: "medium",
    assigneeId: "lena-fischer",
    createdDaysAgo: 24,
    updatedHoursAgo: 24,
  },
  {
    id: "MOB-204",
    title: "Order history stutters with 200+ orders",
    description:
      "Scrolling is janky for customers with long order histories. Paginate the list and render it with a virtualised list instead of a plain ScrollView.",
    status: "open",
    priority: "medium",
    assigneeId: "sam-okafor",
    createdDaysAgo: 19,
    updatedHoursAgo: 120,
  },
  {
    id: "MOB-205",
    title: "Product images show white boxes in dark mode",
    description:
      "Product photos with white backgrounds look like floating boxes in dark mode. Ask the catalogue team for transparent images, or place them in a soft rounded container.",
    status: "open",
    priority: "low",
    assigneeId: null,
    createdDaysAgo: 30,
    updatedHoursAgo: 264,
  },
  {
    id: "MOB-206",
    title: "Deep links from marketing emails open the home screen",
    description:
      "Links like /products/123 in campaign emails open the app but land on Home instead of the product page. iOS only; Android handles them correctly.",
    status: "in_progress",
    priority: "high",
    assigneeId: "maya-chen",
    createdDaysAgo: 6,
    updatedHoursAgo: 4,
  },
  {
    id: "MOB-207",
    title: "Force an upgrade for app versions below 5.2",
    description:
      "Versions below 5.2 still call the legacy checkout endpoints. Show a blocking upgrade screen with a link to the store. Waiting for App Store review of 5.4, which contains the upgrade screen.",
    status: "blocked",
    priority: "high",
    assigneeId: "hana-kim",
    createdDaysAgo: 14,
    updatedHoursAgo: 48,
  },
  {
    id: "MOB-208",
    title: "Barcode scanner will not focus on older iPhones",
    description:
      "On iPhone 11 and older the camera stays blurry when scanning product barcodes. Turn on continuous autofocus and add tap to focus.",
    status: "closed",
    priority: "medium",
    assigneeId: "sam-okafor",
    createdDaysAgo: 37,
    updatedHoursAgo: 624,
  },
  {
    id: "MOB-209",
    title: "Offline banner stays visible after reconnecting",
    description:
      "The 'You are offline' banner does not go away when the connection comes back, only after the user moves to another screen.",
    status: "closed",
    priority: "low",
    assigneeId: "lena-fischer",
    createdDaysAgo: 22,
    updatedHoursAgo: 408,
  },
  {
    id: "MOB-210",
    title: "Support chat loses the draft when the app is backgrounded",
    description:
      "Messages typed in the support chat are lost if the user switches apps to copy an order number. Keep the draft per conversation.",
    status: "open",
    priority: "high",
    assigneeId: "maya-chen",
    createdDaysAgo: 5,
    updatedHoursAgo: 20,
  },
  {
    id: "MOB-211",
    title: "Upgrade to the latest React Native release",
    description:
      "We are two minor versions behind, which blocks the new architecture work and the Android 15 edge-to-edge fixes.",
    status: "in_progress",
    priority: "medium",
    assigneeId: "hana-kim",
    createdDaysAgo: 17,
    updatedHoursAgo: 7,
  },
  {
    id: "MOB-212",
    title: "Removed wishlist items come back after syncing",
    description:
      "Items removed from the wishlist on the website reappear in the app after the next sync. The app merges the lists instead of respecting deletions.",
    status: "open",
    priority: "medium",
    assigneeId: null,
    createdDaysAgo: 12,
    updatedHoursAgo: 72,
  },
  {
    id: "MOB-213",
    title: "Add haptic feedback when adding to cart",
    description:
      "Design wants a light haptic tap when an item is added to the cart, matching the iOS system style. Android should use the closest equivalent.",
    status: "closed",
    priority: "low",
    assigneeId: "lena-fischer",
    createdDaysAgo: 44,
    updatedHoursAgo: 912,
  },
  {
    id: "MOB-214",
    title: "Login screen text is cut off at large font sizes",
    description:
      "With Dynamic Type at the largest accessibility size, the password label and the 'Forgot password?' link are truncated.",
    status: "open",
    priority: "medium",
    assigneeId: "sam-okafor",
    createdDaysAgo: 9,
    updatedHoursAgo: 55,
  },
  {
    id: "MOB-215",
    title: "Measure app start time in production",
    description:
      "Report cold and warm start times to our monitoring so we catch regressions like the one in 5.3.0 before users do.",
    status: "open",
    priority: "medium",
    assigneeId: "hana-kim",
    createdDaysAgo: 26,
    updatedHoursAgo: 192,
  },
  {
    id: "MOB-216",
    title: "Order tracking map shows the courier at the depot",
    description:
      "The map pin stays at the depot until the parcel is delivered. The courier API returns live coordinates, but we read the wrong field. Blocked on production credentials for the courier API.",
    status: "blocked",
    priority: "high",
    assigneeId: "maya-chen",
    createdDaysAgo: 10,
    updatedHoursAgo: 27,
  },
  {
    id: "MOB-217",
    title: "Home carousel keeps advancing for VoiceOver users",
    description:
      "The promo carousel on Home keeps moving while VoiceOver is reading it. Pause autoplay whenever a screen reader is running.",
    status: "open",
    priority: "medium",
    assigneeId: null,
    createdDaysAgo: 16,
    updatedHoursAgo: 144,
  },
  {
    id: "MOB-218",
    title: "Get the iOS download under 50 MB",
    description:
      "The iOS download is 68 MB, mostly bundled fonts and onboarding videos. Stream the videos from the CDN and subset the fonts.",
    status: "in_progress",
    priority: "low",
    assigneeId: "sam-okafor",
    createdDaysAgo: 33,
    updatedHoursAgo: 46,
  },
  {
    id: "MOB-219",
    title: "Password reset links open the website instead of the app",
    description:
      "Reset emails open the web flow even when the app is installed. Add the reset path to the associated domains configuration.",
    status: "closed",
    priority: "high",
    assigneeId: "hana-kim",
    createdDaysAgo: 18,
    updatedHoursAgo: 30,
  },
  {
    id: "MOB-220",
    title: "Android back button discards the checkout form",
    description:
      "Pressing back during checkout closes the sheet and loses the address the customer entered. Ask for confirmation when the form has unsaved changes.",
    status: "open",
    priority: "high",
    assigneeId: "lena-fischer",
    createdDaysAgo: 3,
    updatedHoursAgo: 10,
  },
  {
    id: "MOB-221",
    title: "Show delivery progress in a Live Activity",
    description:
      "iOS users should see their delivery status on the lock screen from dispatch to delivery. Start with the three main states.",
    status: "open",
    priority: "low",
    assigneeId: null,
    createdDaysAgo: 40,
    updatedHoursAgo: 360,
  },
  {
    id: "MOB-222",
    title: "Crash when rotating an iPad in the product gallery",
    description:
      "Rotating the device while zooming into a product image crashes the app on iPad. Handle the layout change during the zoom gesture.",
    status: "closed",
    priority: "medium",
    assigneeId: "sam-okafor",
    createdDaysAgo: 28,
    updatedHoursAgo: 504,
  },
  {
    id: "MOB-223",
    title: "Translate the app into Polish",
    description:
      "Poland is now our fifth largest market. The strings are back from the translation agency; wire up the pl locale and check the plural rules.",
    status: "in_progress",
    priority: "medium",
    assigneeId: "maya-chen",
    createdDaysAgo: 20,
    updatedHoursAgo: 31,
  },
  {
    id: "MOB-224",
    title: "Rating prompt appears right after a failed order",
    description:
      "The review prompt fires on the fifth app open, even if the last thing the user saw was a payment error. Only ask after a successful delivery.",
    status: "open",
    priority: "low",
    assigneeId: "hana-kim",
    createdDaysAgo: 11,
    updatedHoursAgo: 96,
  },
  {
    id: "MOB-225",
    title: "Sign in with Apple fails for hidden email addresses",
    description:
      "Users who chose 'Hide My Email' get 'account not found' on their second sign-in, because we match accounts on email instead of the Apple user id.",
    status: "in_progress",
    priority: "urgent",
    assigneeId: "lena-fischer",
    createdDaysAgo: 3,
    updatedHoursAgo: 5,
  },
  {
    id: "MOB-226",
    title: "Remove the analytics SDKs we no longer use",
    description:
      "We ship three analytics SDKs but only report from one. Remove the other two and update the privacy manifest.",
    status: "closed",
    priority: "low",
    assigneeId: "sam-okafor",
    createdDaysAgo: 48,
    updatedHoursAgo: 984,
  },
];
